package library_hub;

import java.sql.*;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class book extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(book.class.getName());
    
    private String check;
    
    public book() {
        initComponents();
        Connect();
        bookData();
       
    }
    public void updateTable() {
        try {
        // Use the 'con' that was initialized in Connect()
        if (con == null) Connect(); 

        String sql = "SELECT * FROM book"; // Match your table name 'book'
        pst = con.prepareStatement(sql);
        ResultSet rs = pst.executeQuery();

        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.setRowCount(0); 

        while (rs.next()) {
            model.addRow(new Object[]{
                rs.getString("acquisition_no"),
                rs.getString("title"),
                rs.getString("author"),
                rs.getString("date_published"),
                rs.getString("category"),
                rs.getString("status")
            });
        }
        // Update your total count field
        txttotalbook.setText(String.valueOf(model.getRowCount()));
        
    } catch (Exception e) {
        System.out.println("Table Error: " + e.getMessage());
    }
    }
    Connection con;
    PreparedStatement pst;
    
    public void Connect(){
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost/libraryhub","root","");
        } catch (ClassNotFoundException ex) {
            System.getLogger(book.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
        } catch (SQLException ex) {
            System.getLogger(book.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
        }
        
       
    }
    private void bookData(){
        try {
            int QQ;
            
            pst = con.prepareStatement("SELECT * FROM book");
            
            ResultSet Rs = pst.executeQuery();
            
            ResultSetMetaData RSMD = Rs.getMetaData();
            
            QQ = RSMD.getColumnCount();
            
            DefaultTableModel DFG = (DefaultTableModel)jTable1.getModel();
            DFG.setRowCount(0);
            
            while(Rs.next()){
                
                Vector v2 = new Vector();
                
                for(int aa = 1; aa <=QQ; aa++){
                    
                    v2.add(Rs.getString("acquisition_no"));
                    v2.add(Rs.getString("title"));
                    v2.add(Rs.getString("author"));
                    v2.add(Rs.getString("date_published"));
                    v2.add(Rs.getString("category"));
                    v2.add(Rs.getString("status"));
                }
                DFG.addRow(v2);
            }
            int rowCount = DFG.getRowCount();
            txttotalbook.setText(String.valueOf(rowCount));
            
        } catch (SQLException ex) {
            System.getLogger(book.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
                        

     
    public void makeEnable(){
        txtacqnumber.setEnabled(true);
        txttitle.setEnabled(true);
        txtauthor.setEnabled(true);
        txtdatepublished.setEnabled(true);
        cmbcategory.setEnabled(true);
    }
    
    public void setDefault(){
        txtacqnumber.setText("");
        txttitle.setText("");
        txtauthor.setText("");
        txtdatepublished.setText("");

        search.setText("");
        txtacqnumber.setEnabled(false);
        txttitle.setEnabled(false);
        txtauthor.setEnabled(false);
        txtdatepublished.setEnabled(false);
        search.setEnabled(true);
        btnadd.setEnabled(true);
        btnedit.setEnabled(false);
        btndelete.setEnabled(false);
        bookData();
    }
    
    

  
   //// public book() {
   ////     initComponents();
   // }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnborrower = new javax.swing.JButton();
        btnuser = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        btnuser1 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txtacqnumber = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txttitle = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtauthor = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtdatepublished = new javax.swing.JTextField();
        cmbcategory = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        btnadd = new javax.swing.JButton();
        btnedit = new javax.swing.JButton();
        btncancel = new javax.swing.JButton();
        btndelete = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        search = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txttotalbook = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(102, 153, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel1.setText("Library System");

        btnborrower.setBackground(new java.awt.Color(204, 204, 204));
        btnborrower.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        btnborrower.setText("Borrower");
        btnborrower.addActionListener(this::btnborrowerActionPerformed);

        btnuser.setBackground(new java.awt.Color(204, 204, 204));
        btnuser.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        btnuser.setText("User");
        btnuser.addActionListener(this::btnuserActionPerformed);

        jButton1.setBackground(new java.awt.Color(204, 204, 204));
        jButton1.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jButton1.setText("Book");
        jButton1.addActionListener(this::jButton1ActionPerformed);

        btnuser1.setBackground(new java.awt.Color(204, 204, 204));
        btnuser1.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        btnuser1.setText("Dashboard");
        btnuser1.addActionListener(this::btnuser1ActionPerformed);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnborrower, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnuser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnuser1))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnuser1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnborrower)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnuser)
                .addContainerGap(294, Short.MAX_VALUE))
        );

        jPanel5.setBackground(new java.awt.Color(204, 204, 204));

        jLabel2.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Book");

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));

        jLabel3.setText("Enter Acqusition Number: ");

        txtacqnumber.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtacqnumberMouseClicked(evt);
            }
        });
        txtacqnumber.addActionListener(this::txtacqnumberActionPerformed);

        jLabel4.setText("Enter Book Title: ");

        txttitle.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txttitleMouseClicked(evt);
            }
        });

        jLabel5.setText("Enter Book Author: ");

        txtauthor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtauthorMouseClicked(evt);
            }
        });

        jLabel6.setText("Enter Date Published:");

        txtdatepublished.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtdatepublishedMouseClicked(evt);
            }
        });
        txtdatepublished.addActionListener(this::txtdatepublishedActionPerformed);

        cmbcategory.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-Select Category-", "Math", "English", "Science", "Filipino" }));
        cmbcategory.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cmbcategoryMouseClicked(evt);
            }
        });
        cmbcategory.addActionListener(this::cmbcategoryActionPerformed);

        jLabel7.setText("Select Category:");

        btnadd.setBackground(new java.awt.Color(204, 204, 204));
        btnadd.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnadd.setText("Add");
        btnadd.addActionListener(this::btnaddActionPerformed);

        btnedit.setBackground(new java.awt.Color(204, 204, 204));
        btnedit.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnedit.setText("Edit");
        btnedit.addActionListener(this::btneditActionPerformed);

        btncancel.setBackground(new java.awt.Color(204, 204, 204));
        btncancel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btncancel.setText("Cancel");
        btncancel.addActionListener(this::btncancelActionPerformed);

        btndelete.setBackground(new java.awt.Color(204, 204, 204));
        btndelete.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btndelete.setText("Delete");
        btndelete.addActionListener(this::btndeleteActionPerformed);

        jTable1.setBackground(new java.awt.Color(153, 204, 255));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Acqusition Number", "Book Title", "Author", "Date Published", "Category", "Status"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jLabel8.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel8.setText("Book List's");

        jLabel9.setText("Search");

        search.addActionListener(this::searchActionPerformed);
        search.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                searchKeyReleased(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jLabel10.setText("Total book number : ");

        txttotalbook.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txttotalbook.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txttotalbook.addActionListener(this::txttotalbookActionPerformed);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 763, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(search, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(59, 59, 59)
                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txttotalbook, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(btnedit)
                                .addGroup(jPanel6Layout.createSequentialGroup()
                                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txttitle)
                                        .addComponent(txtauthor)
                                        .addComponent(txtdatepublished)
                                        .addComponent(cmbcategory, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(txtacqnumber, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel6Layout.createSequentialGroup()
                                            .addGap(29, 29, 29)
                                            .addComponent(btnadd))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(btncancel, javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(btndelete, javax.swing.GroupLayout.Alignment.TRAILING)))))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtacqnumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txttitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtauthor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txtdatepublished, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(cmbcategory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(btnadd)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnedit)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btncancel)
                        .addGap(25, 25, 25)
                        .addComponent(btndelete)))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(search, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(7, 7, 7))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(txttotalbook, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(327, 327, 327)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 3, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtacqnumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtacqnumberActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txtacqnumberActionPerformed

    private void txtdatepublishedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtdatepublishedActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtdatepublishedActionPerformed

    private void btnborrowerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnborrowerActionPerformed
       
    }//GEN-LAST:event_btnborrowerActionPerformed

    private void searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchActionPerformed

    private void btnaddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaddActionPerformed
        try {
            // 1. Validation Check
        if (txtacqnumber.getText().trim().isEmpty() ||
        txttitle.getText().trim().isEmpty() || 
        txtauthor.getText().trim().isEmpty() ||
        txtdatepublished.getText().trim().isEmpty() ||
        cmbcategory.getSelectedIndex() == -1 || // Checks if nothing is selected
        cmbcategory.getSelectedItem().toString().equals("Select Category")) { // Adjust this to match your default placeholder text
        
        JOptionPane.showMessageDialog(this, "Please fill in the blanks");
        return; // This stops the method from continuing to the database part
    }
            makeEnable();
            String bookacq = txtacqnumber.getText();
            String booktitle = txttitle.getText();
            String author = txtauthor.getText();
            String datepublished = txtdatepublished.getText();
            String category = (String) cmbcategory.getSelectedItem();
            
            

            pst = con.prepareStatement("INSERT INTO `book`(`acquisition_no`,`title`,`author`,`date_published`,`category`,`status`)VALUES(?,?,?,?,?,?)");

            pst.setString(1, bookacq);
            pst.setString(2, booktitle);
            pst.setString(3, author);
            pst.setString(4, datepublished);
            pst.setString(5, category);
            pst.setString(6, "Available");

            pst.executeUpdate();
            JOptionPane.showMessageDialog(this, "Record Added Successfully");
            bookData();
        } catch (SQLException ex) {
            System.getLogger(book.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
            
        }
        
    }//GEN-LAST:event_btnaddActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        DefaultTableModel tblModel = (DefaultTableModel) jTable1.getModel();
        int selectedRow =  jTable1.getSelectedRow();

        txtacqnumber.setText(tblModel.getValueAt(selectedRow, 0).toString());
        txttitle.setText(tblModel.getValueAt(selectedRow, 1).toString());
        txtauthor.setText(tblModel.getValueAt(selectedRow, 2).toString());
        txtdatepublished.setText(tblModel.getValueAt(selectedRow, 3).toString());
        cmbcategory.setSelectedItem(tblModel.getValueAt(selectedRow, 4));
        
//setSeletedItem(tblModel.getValueAt(selectedRow, 4).toString());

        btnadd.setEnabled(false);
        btnedit.setEnabled(true);
        btndelete.setEnabled(true);
        btncancel.setText("Cancel");
    }//GEN-LAST:event_jTable1MouseClicked

    private void btneditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneditActionPerformed
        // TODO add your handling code here:
        try {
            String bookacq = txtacqnumber.getText();
            String booktitle = txttitle.getText();
            String author = txtauthor.getText();
            String datepublished = txtdatepublished.getText();
            String category = cmbcategory.getSelectedItem().toString();
                

            pst = con.prepareStatement("UPDATE book SET title = ?,author= ?,date_published= ?, category=? where acquisition_no= ?");

            pst.setString(1, booktitle);
            pst.setString(2, author);
            pst.setString(3, datepublished);
            pst.setString(4, category);
            pst.setString(5, bookacq);

            pst.executeUpdate();
            //JOptionPane.showMessageDialog(this, "Record Edited Successfully");
            bookData();

        } catch (SQLException ex) {
            System.getLogger(book.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
        } 
    }//GEN-LAST:event_btneditActionPerformed

    private void btndeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndeleteActionPerformed
            int row = jTable1.getSelectedRow();
    
    if (row == -1) {
        JOptionPane.showMessageDialog(this, "Please select a book from the table!");
        return;
    }

    // Get the specific ID from the selected row (Column 0 is Acq Number)
    String idToDelete = jTable1.getValueAt(row, 0).toString();

    int dialogResult = JOptionPane.showConfirmDialog(null, "Do you want to Delete this record?", "Warning", JOptionPane.YES_NO_OPTION);
    if (dialogResult == JOptionPane.YES_OPTION) {
        try {
            // Target ONLY this specific acquisition number
            pst = con.prepareStatement("DELETE FROM book WHERE acquisition_no = ? LIMIT 1");
            pst.setString(1, idToDelete);
            pst.executeUpdate();
            
            JOptionPane.showMessageDialog(this, "Record Deleted Successfully");
            
            // Refresh the table and clear fields
            updateTable();
            setDefault(); 
            
        } catch (SQLException ex) {
            Logger.getLogger(book.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    }//GEN-LAST:event_btndeleteActionPerformed

    private void btncancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncancelActionPerformed
        // TODO add your handling code here:
        if(btncancel.getText().equals("Cancel")){
            txtacqnumber.setText("");
            txttitle.setText("");
            txtauthor.setText("");
            txtdatepublished.setText("");
            cmbcategory.setSelectedIndex(0);

        // 2. Shift focus away from the text fields to "deselect" them
            jPanel1.requestFocus();
        } else {
            setDefault();
        }
    }//GEN-LAST:event_btncancelActionPerformed

    private void searchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchKeyReleased
        // TODO add your handling code here:
        String uname = search.getText();

    // Use a parameterized query to prevent SQL Injection
    String query = "SELECT * FROM book WHERE title LIKE ? OR category LIKE ? OR author LIKE ?";

    try {
        Connection con = MySQLConnect.getConnection();
        PreparedStatement pst = con.prepareStatement(query);

        // Prepare the search pattern (e.g., %searchTerm%)
       String searchPattern = "%" + uname + "%";

        // Set parameters (JDBC starts at index 1)
        pst.setString(1, searchPattern);
        pst.setString(2, searchPattern); 
        pst.setString(3, searchPattern); 

        ResultSet rs = pst.executeQuery(); // Note: No 'query' string inside parentheses here

        DefaultTableModel tblModel = (DefaultTableModel) jTable1.getModel();
        tblModel.setRowCount(0); // Clear existing rows

        while (rs.next()) {
            Vector<String> colData = new Vector<>();
            colData.add(rs.getString("acquisition_no"));
            colData.add(rs.getString("title"));
            colData.add(rs.getString("author"));
            colData.add(rs.getString("date_published"));
            colData.add(rs.getString("category"));
            colData.add(rs.getString("status"));

            tblModel.addRow(colData);
        }

    } catch (SQLException e) {
        JOptionPane.showMessageDialog(null, "Database Error: " + e.getMessage());
    }
    }//GEN-LAST:event_searchKeyReleased

    private void cmbcategoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbcategoryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbcategoryActionPerformed

    private void txtacqnumberMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtacqnumberMouseClicked
        // TODO add your handling code here:
        btnadd.setEnabled(true);
    }//GEN-LAST:event_txtacqnumberMouseClicked

    private void txttitleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txttitleMouseClicked
        // TODO add your handling code here:
        btnadd.setEnabled(true);
    }//GEN-LAST:event_txttitleMouseClicked

    private void txtauthorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtauthorMouseClicked
        // TODO add your handling code here:
        btnadd.setEnabled(true);
    }//GEN-LAST:event_txtauthorMouseClicked

    private void txtdatepublishedMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtdatepublishedMouseClicked
        // TODO add your handling code here:
        btnadd.setEnabled(true);
    }//GEN-LAST:event_txtdatepublishedMouseClicked

    private void cmbcategoryMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmbcategoryMouseClicked
        // TODO add your handling code here:
        btnadd.setEnabled(true);
    }//GEN-LAST:event_cmbcategoryMouseClicked

    private void btnuserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnuserActionPerformed
        
    }//GEN-LAST:event_btnuserActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        book b = new book();
        b.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txttotalbookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txttotalbookActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txttotalbookActionPerformed

    private void btnuser1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnuser1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnuser1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new book().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnadd;
    private javax.swing.JButton btnborrower;
    private javax.swing.JButton btncancel;
    private javax.swing.JButton btndelete;
    private javax.swing.JButton btnedit;
    private javax.swing.JButton btnuser;
    private javax.swing.JButton btnuser1;
    private javax.swing.JComboBox<String> cmbcategory;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField search;
    private javax.swing.JTextField txtacqnumber;
    private javax.swing.JTextField txtauthor;
    private javax.swing.JTextField txtdatepublished;
    private javax.swing.JTextField txttitle;
    private javax.swing.JTextField txttotalbook;
    // End of variables declaration//GEN-END:variables
        }
